### PR TITLE
Test code sparsity effect on JIT compilation time

### PR DESCRIPTION
**Pull request by thalassemia**
I created a script to convert the lambdas into functions. In `refactored.py`, I told the script to explicitly write out each array assignment, including all the redundant `arr[i, j] = 0` lines. In `refactored_sparse.py`, I omitted these redundant lines.

This simple change takes advantage of the sparse nature of the Jacobians and greatly improves their slow compilation time. 

```
Numba timings on Python 3.11.4 on Linux-6.2.0-36-generic-x86_64-with-glibc2.35
tcs_rates_sp                0.009772516507655381 ms, jitting 722.3593890666962 ms, jitted 0.00094614929985255 ms, iterations to payoff 81,841
tcs_rates_jac_sp            0.01033625619020313 ms, jitting 427.2203661967069 ms, jitted 0.0011098834918811917 ms, iterations to payoff 46,304
eq_rates_sp                 0.019501695595681667 ms, jitting 764.8624428547919 ms, jitted 0.0009970564162358642 ms, iterations to payoff 41,334
eq_rates_jac_sp             0.02400527570862323 ms, jitting 1,089.303818065673 ms, jitted 0.0019190067891031505 ms, iterations to payoff 49,320
tcs_rates                   0.00795334291178733 ms, jitting 328.61273596063256 ms, jitted 0.0009136812994256615 ms, iterations to payoff 46,680
tcs_rates_jac               0.10345246579963714 ms, jitting 24,354.846538975835 ms, jitted 0.0012056021019816398 ms, iterations to payoff 238,197
eq_rates                    0.019233635789714754 ms, jitting 747.4193319212645 ms, jitted 0.000989661389030516 ms, iterations to payoff 40,968
eq_rates_jac                0.3213376781903207 ms, jitting 368,050.12288712896 ms, jitted 0.0022401002002879976 ms, iterations to payoff 1,153,409
2CS RATES                   0.012329716701060534 ms, jitting 491.349833086133 ms, jitted 0.003364824107848108 ms, iterations to payoff 54,808
2CS RATES JACOBIAN          0.084670475916937 ms, jitting 26,302.62542096898 ms, jitted 0.014886920200660826 ms, iterations to payoff 376,917
EQUILIBRIUM RATES           0.02523207301273942 ms, jitting 1,351.658636936918 ms, jitted 0.004280653595924377 ms, iterations to payoff 64,514
EQUILIBRIUM RATES JACOBIAN  0.2544693194096908 ms, jitting 228,644.82728694566 ms, jitted 0.04940405329689383 ms, iterations to payoff 1,114,986
```

### CODE REVIEW

**Comment by thalassemia** [comment]
I still have to do more testing on different versions of Python.

**Comment by 1fish2** [comment]
Smart idea!

I was relying on Numba + llvm to do all the optimization, but this idea goes further to optimize the compiler's work, not just its output.

These expressions used to have more subexpressions like `y[76] ** 1.0`, but either Sympy is smarter now or I'm mixing them up with the ones that the Parca caches. IIRC the Parca's cache can't use `def` functions to a source file for some reason...

I'll test and merge this tomorrow, but probably won't get to it until after our meeting.

Meanwhile, this code needn't write functions to a source file; it could still build a lambda expression.

```python
def tcs_rates_sp(t, y, kf, kr):
	arr = np.zeros((29, 1))
	arr[0, 0] = 500.0*y[3]*y[4]
	arr[1, 0] = 100000000.0*y[0]*y[6]
	...
	return arr.reshape(-1)
```

could be
```python
lambda t, y, kf, kr: builder((29, 1),
    (0, 0, 500.0*y[3]*y[4]),
    (1, 0, 100000000.0*y[0]*y[6]),
    ...)
```

where we'd pass in a builder subroutine to `eval()` as a local or global binding:

```python
def builder(dims, *entries):
    a = np.zeros(dims, float)
    for i, j, e in entries:
        a[i, j] = e
    return a.reshape(-1)
```

And rather than building a 2-D array using 2-D indexing then linearizing it via `reshape(-1)`, this could just build a 1-D array if we don't mind doing more SymPy work at compile time.

**Comment by 1fish2** [comment]
Or use run-length coding for the zeros so the lambda function doesn't need to pass indexes to the builder. The builder would take float values as successive array entries and a value like `[3]` to mean 3 successive zeros.

**Comment by thalassemia** [comment]
Here are the timings for Python 3.8.13.

```
Numba timings on Python 3.8.13 on Linux-6.2.0-36-generic-x86_64-with-glibc2.34
tcs_rates_sp                0.009063484310172497 ms, jitting 855.8187910821289 ms, jitted 0.0010295036947354675 ms, iterations to payoff 106,525
tcs_rates_jac_sp            0.011342929000966251 ms, jitting 540.5529940035194 ms, jitted 0.001217639190144837 ms, iterations to payoff 53,386
eq_rates_sp                 0.02099986160174012 ms, jitting 952.5412558577955 ms, jitted 0.0011072135996073485 ms, iterations to payoff 47,884
eq_rates_jac_sp             0.025259154988452794 ms, jitting 1,310.7536400202662 ms, jitted 0.0020732861012220383 ms, iterations to payoff 56,532
tcs_rates                   0.008302606898359955 ms, jitting 403.0446361284703 ms, jitted 0.0010213875910267233 ms, iterations to payoff 55,354
tcs_rates_jac               0.10877740818541497 ms, jitting 26,116.256455890834 ms, jitted 0.0012831341940909625 ms, iterations to payoff 242,955
eq_rates                    0.02154928131494671 ms, jitting 950.131599791348 ms, jitted 0.0011017316021025181 ms, iterations to payoff 46,467
eq_rates_jac                0.3486484591849148 ms, jitting 377,688.22030304 ms, jitted 0.0022704926086589694 ms, iterations to payoff 1,090,393
2CS RATES                   0.012629155698232353 ms, jitting 590.7499638851732 ms, jitted 0.0034659776836633684 ms, iterations to payoff 64,470
2CS RATES JACOBIAN          0.07725068780127912 ms, jitting 1,827.3704540915787 ms, jitted 0.005176899489015341 ms, iterations to payoff 25,354
EQUILIBRIUM RATES           0.025814494793303312 ms, jitting 1,050.7654729299247 ms, jitted 0.004161605308763683 ms, iterations to payoff 48,528
EQUILIBRIUM RATES JACOBIAN  0.25033990738447753 ms, jitting 9,327.043486991897 ms, jitted 0.009670276893302798 ms, iterations to payoff 38,755
```

A few observations:
1. Compilation of the non-sparsified functions is just as slow in Python 3.8 as it is in Python 3.11. Perhaps Numba removes implicit no-ops in `np.array([...])` during compilation in Python 3.8 but not in Python 3.11.
2.  Before JIT compilation, the sparsified `arr[i,j] = k` functions are faster than the `np.array([...])` lambdas by a factor that scales with array size (up to a 10x improvement for equilibrium rates Jacobian). 
3. Before JIT compilation, the non-sparsified `arr[i,j] = k` functions are faster than the `np.array([...])` lambdas for small arrays (non-Jacobians) but slower for large arrays (Jacobians).
4. After JIT compilation, all `arr[i,j]= k` functions (sparsified and non-sparsified) are approximately 4x faster than their `np.array([...])` counterparts.
5. There is some internal caching happening in Numba that makes it hard to accurately measure compilation time. For example, `tcs_rates`, `tcs_rates_sp` and `2CS RATES` all compile in around 850 ms when run in their own Python 3.8 interpreters. However, in the timings above, `tcs_rates` and `2CS RATES` finish compiling in about 550 ms each. Accounting for this, all sparsified `arr[i,j] = k` functions compile more quickly than their `np.array([...])` counterparts.

The builder function is a cool idea! I tested it and got the following timings:
```
Numba timings on Python 3.8.13 on Linux-6.2.0-36-generic-x86_64-with-glibc2.34
tcs_rates_sp_lambda         0.16013820129446685 ms, jitting 980.3120188880712 ms, jitted 0.0010185677092522383 ms, iterations to payoff 6,161
tcs_rates_jac_sp_lambda     0.09279975530225784 ms, jitting 1,107.2439490817487 ms, jitted 0.001223413902334869 ms, iterations to payoff 12,091
eq_rates_sp_lambda          0.07229560590349138 ms, jitting 1,244.5944100618362 ms, jitted 0.0010880968999117614 ms, iterations to payoff 17,478
eq_rates_jac_sp_lambda      0.19662093590013682 ms, jitting 2,544.8495890013874 ms, jitted 0.0021884894929826257 ms, iterations to payoff 13,089
```
The pre-JIT runtime for `tcs_rates_sp_lambda` is skewed by the first-run compilation time for `builder`, which I had to decorate with `@njit` for Numba to work. JIT compilation of these lambdas is substantially slower than that for the functions I wrote to disk.  However, the post-JIT performance is comparable and still much better than we are currently getting with the jitted `np.array([...])` lambdas.

**Comment by thalassemia** [comment]
The JIT compilation performance for the `builder` lambdas is even worse in Python 3.11.
```
Numba timings on Python 3.11.4 on Linux-6.2.0-36-generic-x86_64-with-glibc2.35
tcs_rates_sp_lambda         0.1300076751038432 ms, jitting 829.785292968154 ms, jitted 0.000982124893926084 ms, iterations to payoff 6,431
tcs_rates_jac_sp_lambda     0.08111479638610035 ms, jitting 2,306.4968809485435 ms, jitted 0.0011416921857744454 ms, iterations to payoff 28,841
eq_rates_sp_lambda          0.06468541489448398 ms, jitting 1,614.3540390767157 ms, jitted 0.0010714292991906406 ms, iterations to payoff 25,377
eq_rates_jac_sp_lambda      0.18677633081097156 ms, jitting 7,463.543115183711 ms, jitted 0.0023194144014269114 ms, iterations to payoff 40,462
```
My solution of writing functions to disk does not scale well to the case of running many simultaneous simulations with potentially different rate matrices. Maybe we could use `exec`? I think it's worth pursuing since it shaves entire seconds off the compilation time.

Timings with `exec`
```
Numba timings on Python 3.11.4 on Linux-6.2.0-36-generic-x86_64-with-glibc2.35
tcs_rates_sp                0.007913300907239318 ms, jitting 704.5247161295265 ms, jitted 0.0008936874102801085 ms, iterations to payoff 100,365
tcs_rates_jac_sp            0.010273903398774565 ms, jitting 451.6659260261804 ms, jitted 0.0010897665051743388 ms, iterations to payoff 49,179
eq_rates_sp                 0.019561029714532198 ms, jitting 773.2016069348902 ms, jitted 0.000959905399940908 ms, iterations to payoff 41,567
eq_rates_jac_sp             0.0239878618856892 ms, jitting 1,086.489437147975 ms, jitted 0.0018903617979958653 ms, iterations to payoff 49,168
```

**Comment by 1fish2** [comment]
Excellent! This reveals more about which cases are slow on which Python versions, a surprising way to speed them up, and how many times we need to call the functions to get a payoff from JIT-compiling them.

**Comment by 1fish2** [comment]
@thalassemia I made the output format Markdown-friendly, added your "few observations" and sample output to `observations.md`, added `_def` functions to show the surprising behavior in the first observation. Feel free to add more observations and/or output captures. This should help the Numba team debug it.

**Pull request merged**
